// ********RoostGPT********
/*
Test generated by RoostGPT for test akshat-shared-test-1 using AI Type  and AI Model

ROOST_METHOD_HASH=setB_dd5b9e9525
ROOST_METHOD_SIG_HASH=setB_cba279c0b1

"""
Scenario 1: Validate setB method with positive integer
Details:
  TestName: validateSetBWithPositiveInteger
  Description: This test is meant to check if the setB method sets the value of b correctly when a positive integer is passed.
Execution:
  Arrange: Instantiate the Calculator class and set value of a using setA method.
  Act: Invoke setB method with a positive integer.
  Assert: Use getSum and getProduct methods to check if b has been set correctly.
Validation:
  The assertion aims to verify if the value of b has been set correctly. If b is set correctly, the sum and product calculated should match the expected values. This test is significant as it validates the basic functionality of the setB method.

Scenario 2: Validate setB method with negative integer
Details:
  TestName: validateSetBWithNegativeInteger
  Description: This test is meant to check if the setB method sets the value of b correctly when a negative integer is passed.
Execution:
  Arrange: Instantiate the Calculator class and set value of a using setA method.
  Act: Invoke setB method with a negative integer.
  Assert: Use getSum and getProduct methods to check if b has been set correctly.
Validation:
  The assertion aims to verify if the value of b has been set correctly, even when a negative number is passed. If b is set correctly, the sum and product calculated should match the expected values. This test is significant as it validates the functionality of the setB method with negative numbers.

Scenario 3: Validate setB method with zero
Details:
  TestName: validateSetBWithZero
  Description: This test is meant to check if the setB method sets the value of b correctly when zero is passed.
Execution:
  Arrange: Instantiate the Calculator class and set value of a using setA method.
  Act: Invoke setB method with zero.
  Assert: Use getSum and getProduct methods to check if b has been set correctly.
Validation:
  The assertion aims to verify if the value of b has been set correctly when zero is passed. If b is set correctly, the sum and product calculated should match the expected values. This test is significant as it validates the functionality of the setB method with zero as input.
"""
*/

// ********RoostGPT********

package br.masmangan.beecrowd.bee1001;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;

public class CalculatorSetBTest {

	@Test
	@Tag("valid")
	public void validateSetBWithPositiveInteger() {
		Calculator calculator = new Calculator();
		calculator.setA(5);
		calculator.setB(3);
		assertEquals(8, calculator.getSum());
		assertEquals(15, calculator.getProduct());
	}

	@Test
	@Tag("valid")
	public void validateSetBWithNegativeInteger() {
		Calculator calculator = new Calculator();
		calculator.setA(5);
		calculator.setB(-3);
		assertEquals(2, calculator.getSum());
		assertEquals(-15, calculator.getProduct());
	}

	@Test
	@Tag("boundary")
	public void validateSetBWithZero() {
		Calculator calculator = new Calculator();
		calculator.setA(5);
		calculator.setB(0);
		assertEquals(5, calculator.getSum());
		assertEquals(0, calculator.getProduct());
	}

}