
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-unit-new using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=getAverage_3b87df4523
ROOST_METHOD_SIG_HASH=getAverage_5d8b4919d3

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-unit-new/e8bd33a2-ce7e-43f8-8bac-70ae1c3057a5/source/java-cucumber/src/test/java/br/masmangan/beecrowd/bee1005/StudentGradeSteps.java
Tests:
    "@Test
public void average_is_calculated() {
    actual = equation.getAverage();
}
"

File Path: /var/tmp/Roost/RoostGPT/java-unit-new/e8bd33a2-ce7e-43f8-8bac-70ae1c3057a5/source/java-cucumber/src/test/java/br/masmangan/beecrowd/bee1006/StudentGradeSteps.java
Tests:
    "@Test
public void average_is_calculated() {
    actual = equation.getAverage();
}
"Scenario 1: Average Calculation with Positive Values

Details:
  TestName: averageCalculationWithPositiveValues
  Description: This test checks if the getAverage method correctly calculates the average when all grades (a, b, c) are positive.
Execution:
  Arrange: Set a = 5.0, b = 6.0, c = 7.0.
  Act: Call getAverage().
  Assert: Expect the result to be (5.0 * 2.0 + 6.0 * 3.0 + 7.0 * 5.0) / 10.0 = 6.4.
Validation:
  This test ensures that the average is calculated correctly when all grades are positive. It verifies the basic functionality of the getAverage method.

Scenario 2: Average Calculation with Negative Values

Details:
  TestName: averageCalculationWithNegativeValues
  Description: This test checks if the getAverage method correctly calculates the average when all grades (a, b, c) are negative.
Execution:
  Arrange: Set a = -5.0, b = -6.0, c = -7.0.
  Act: Call getAverage().
  Assert: Expect the result to be (-5.0 * 2.0 + -6.0 * 3.0 + -7.0 * 5.0) / 10.0 = -6.4.
Validation:
  This test ensures that the average is calculated correctly when all grades are negative. It verifies the method's handling of negative values.

Scenario 3: Average Calculation with Zero Values

Details:
  TestName: averageCalculationWithZeroValues
  Description: This test checks if the getAverage method correctly calculates the average when all grades (a, b, c) are zero.
Execution:
  Arrange: Set a = 0.0, b = 0.0, c = 0.0.
  Act: Call getAverage().
  Assert: Expect the result to be (0.0 * 2.0 + 0.0 * 3.0 + 0.0 * 5.0) / 10.0 = 0.0.
Validation:
  This test ensures that the average is calculated correctly when all grades are zero. It verifies the method's handling of zero values.

Scenario 4: Average Calculation with Mixed Positive and Negative Values

Details:
  TestName: averageCalculationWithMixedValues
  Description: This test checks if the getAverage method correctly calculates the average when grades (a, b, c) include both positive and negative values.
Execution:
  Arrange: Set a = 3.0, b = -4.0, c = 5.0.
  Act: Call getAverage().
  Assert: Expect the result to be (3.0 * 2.0 + -4.0 * 3.0 + 5.0 * 5.0) / 10.0 = 2.8.
Validation:
  This test ensures that the average is calculated correctly when grades include both positive and negative values. It verifies the method's handling of mixed values.

Scenario 5: Average Calculation with Large Values

Details:
  TestName: averageCalculationWithLargeValues
  Description: This test checks if the getAverage method correctly calculates the average when grades (a, b, c) are large positive values.
Execution:
  Arrange: Set a = 1000.0, b = 2000.0, c = 3000.0.
  Act: Call getAverage().
  Assert: Expect the result to be (1000.0 * 2.0 + 2000.0 * 3.0 + 3000.0 * 5.0) / 10.0 = 2400.0.
Validation:
  This test ensures that the average is calculated correctly when grades are large positive values. It verifies the method's handling of large values.

Scenario 6: Average Calculation with Small Values

Details:
  TestName: averageCalculationWithSmallValues
  Description: This test checks if the getAverage method correctly calculates the average when grades (a, b, c) are small positive values.
Execution:
  Arrange: Set a = 0.1, b = 0.2, c = 0.3.
  Act: Call getAverage().
  Assert: Expect the result to be (0.1 * 2.0 + 0.2 * 3.0 + 0.3 * 5.0) / 10.0 = 0.18.
Validation:
  This test ensures that the average is calculated correctly when grades are small positive values. It verifies the method's handling of small values.

Scenario 7: Average Calculation with Maximum Double Values

Details:
  TestName: averageCalculationWithMaxDoubleValues
  Description: This test checks if the getAverage method correctly calculates the average when grades (a, b, c) are set to the maximum value of a double.
Execution:
  Arrange: Set a = Double.MAX_VALUE, b = Double.MAX_VALUE, c = Double.MAX_VALUE.
  Act: Call getAverage().
  Assert: Expect the result to be (Double.MAX_VALUE * 2.0 + Double.MAX_VALUE * 3.0 + Double.MAX_VALUE * 5.0) / 10.0.
Validation:
  This test ensures that the average is calculated correctly when grades are set to the maximum value of a double. It verifies the method's handling of extreme values.

Scenario 8: Average Calculation with Minimum Double Values

Details:
  TestName: averageCalculationWithMinDoubleValues
  Description: This test checks if the getAverage method correctly calculates the average when grades (a, b, c) are set to the minimum value of a double.
Execution:
  Arrange: Set a = Double.MIN_VALUE, b = Double.MIN_VALUE, c = Double.MIN_VALUE.
  Act: Call getAverage().
  Assert: Expect the result to be (Double.MIN_VALUE * 2.0 + Double.MIN_VALUE * 3.0 + Double.MIN_VALUE * 5.0) / 10.0.
Validation:
  This test ensures that the average is calculated correctly when grades are set to the minimum value of a double. It verifies the method's handling of extreme values.

Scenario 9: Average Calculation with NaN Values

Details:
  TestName: averageCalculationWithNaNValues
  Description: This test checks if the getAverage method correctly handles NaN values in grades (a, b, c).
Execution:
  Arrange: Set a = Double.NaN, b = Double.NaN, c = Double.NaN.
  Act: Call getAverage().
  Assert: Expect the result to be NaN.
Validation:
  This test ensures that the average is correctly handled when grades include NaN values. It verifies the method's handling of invalid values.

Scenario 10: Average Calculation with Infinity Values

Details:
  TestName: averageCalculationWithInfinityValues
  Description: This test checks if the getAverage method correctly handles Infinity values in grades (a, b, c).
Execution:
  Arrange: Set a = Double.POSITIVE_INFINITY, b = Double.POSITIVE_INFINITY, c = Double.POSITIVE_INFINITY.
  Act: Call getAverage().
  Assert: Expect the result to be Infinity.
Validation:
  This test ensures that the average is correctly handled when grades include Infinity values. It verifies the method's handling of infinite values.

*/

// ********RoostGPT********

package br.masmangan.beecrowd.bee1006;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;

public class StudentGradeGetAverageTest {

	private StudentGrade studentGrade;

	@BeforeEach
	public void setUp() {
		studentGrade = new StudentGrade();
	}

	@Test
	@Tag("valid")
	public void averageCalculationWithPositiveValues() {
		studentGrade.setA(5.0);
		studentGrade.setB(6.0);
		studentGrade.setC(7.0);
		assertEquals(6.4, studentGrade.getAverage(), 0.0001);
	}

	@Test
	@Tag("valid")
	public void averageCalculationWithNegativeValues() {
		studentGrade.setA(-5.0);
		studentGrade.setB(-6.0);
		studentGrade.setC(-7.0);
		assertEquals(-6.4, studentGrade.getAverage(), 0.0001);
	}

	@Test
	@Tag("valid")
	public void averageCalculationWithZeroValues() {
		studentGrade.setA(0.0);
		studentGrade.setB(0.0);
		studentGrade.setC(0.0);
		assertEquals(0.0, studentGrade.getAverage(), 0.0001);
	}

	@Test
	@Tag("valid")
	public void averageCalculationWithMixedValues() {
		studentGrade.setA(3.0);
		studentGrade.setB(-4.0);
		studentGrade.setC(5.0);
		assertEquals(2.8, studentGrade.getAverage(), 0.0001);
	}

	@Test
	@Tag("valid")
	public void averageCalculationWithLargeValues() {
		studentGrade.setA(1000.0);
		studentGrade.setB(2000.0);
		studentGrade.setC(3000.0);
		assertEquals(2400.0, studentGrade.getAverage(), 0.0001);
	}

	@Test
	@Tag("valid")
	public void averageCalculationWithSmallValues() {
		studentGrade.setA(0.1);
		studentGrade.setB(0.2);
		studentGrade.setC(0.3);
		assertEquals(0.18, studentGrade.getAverage(), 0.0001);
	}

	@Test
	@Tag("boundary")
	public void averageCalculationWithMaxDoubleValues() {
		studentGrade.setA(Double.MAX_VALUE);
		studentGrade.setB(Double.MAX_VALUE);
		studentGrade.setC(Double.MAX_VALUE);
		assertEquals((Double.MAX_VALUE * 2.0 + Double.MAX_VALUE * 3.0 + Double.MAX_VALUE * 5.0) / 10.0,
				studentGrade.getAverage(), 0.0001);
	}

	@Test
	@Tag("boundary")
	public void averageCalculationWithMinDoubleValues() {
		studentGrade.setA(Double.MIN_VALUE);
		studentGrade.setB(Double.MIN_VALUE);
		studentGrade.setC(Double.MIN_VALUE);
		assertEquals((Double.MIN_VALUE * 2.0 + Double.MIN_VALUE * 3.0 + Double.MIN_VALUE * 5.0) / 10.0,
				studentGrade.getAverage(), 0.0001);
	}

	@Test
	@Tag("invalid")
	public void averageCalculationWithNaNValues() {
		studentGrade.setA(Double.NaN);
		studentGrade.setB(Double.NaN);
		studentGrade.setC(Double.NaN);
		assertEquals(Double.NaN, studentGrade.getAverage(), 0.0001);
	}

	@Test
	@Tag("invalid")
	public void averageCalculationWithInfinityValues() {
		studentGrade.setA(Double.POSITIVE_INFINITY);
		studentGrade.setB(Double.POSITIVE_INFINITY);
		studentGrade.setC(Double.POSITIVE_INFINITY);
		assertEquals(Double.POSITIVE_INFINITY, studentGrade.getAverage(), 0.0001);
	}

}