/*
 * Copyright (C) 2021, Gherkin By Example and/or its contributors. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This software is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This code is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this code.  If not, see <https://www.gnu.org/licenses/>.
 *
 * Please visit Gherkin By Example at https://github.com/gherkin-by-example
 * if you need additional information or have any questions.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test new-test-1 using AI Type  and AI Model 

ROOST_METHOD_HASH=getArea_db993df5e2
ROOST_METHOD_SIG_HASH=getArea_fc67037257

"""
Scenario 1: Test for Zero Radius
Details:  
  TestName: testAreaWithZeroRadius
  Description: This test checks if the getArea method returns 0 when the radius is set to 0.
Execution:
  Arrange: Set the radius of the Circle object to 0 using the setRadius method.
  Act: Invoke the getArea method on the Circle object.
  Assert: Assert that the returned area is 0.
Validation: 
  The assertion verifies that the area of a circle with zero radius is indeed 0. This is important to ensure the getArea method correctly calculates the area in edge cases.

Scenario 2: Test for Positive Radius
Details:  
  TestName: testAreaWithPositiveRadius
  Description: This test checks if the getArea method returns the correct area when the radius is a positive number.
Execution:
  Arrange: Set the radius of the Circle object to a known positive number using the setRadius method.
  Act: Invoke the getArea method on the Circle object.
  Assert: Assert that the returned area matches the expected value calculated manually.
Validation: 
  The assertion verifies that the area of a circle with a positive radius is correctly calculated. This is the standard use case for the getArea method.

Scenario 3: Test for Negative Radius
Details:  
  TestName: testAreaWithNegativeRadius
  Description: This test checks if the getArea method handles the scenario where the radius is negative.
Execution:
  Arrange: Set the radius of the Circle object to a negative number using the setRadius method.
  Act: Invoke the getArea method on the Circle object.
  Assert: Assert that the returned area is NaN (Not a Number) or throws an appropriate exception.
Validation: 
  The assertion verifies that the getArea method correctly handles invalid input (negative radius). This is important for ensuring the robustness of the method.
"""
*/

// ********RoostGPT********

package br.masmangan.beecrowd.bee1002;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.*;

public class CircleGetAreaTest {
    @Test
    @Tag("boundary")
    public void testAreaWithZeroRadius() {
        Circle circle = new Circle();
        circle.setRadius(0.0);
        double actualArea = circle.getArea();
        assertEquals(0.0, actualArea, "Area of circle with radius 0 should be 0");
    }
    @Test
    @Tag("valid")
    public void testAreaWithPositiveRadius() {
        Circle circle = new Circle();
        circle.setRadius(5.0);
        double actualArea = circle.getArea();
        double expectedArea = Circle.PI * 5.0 * 5.0;
        assertEquals(expectedArea, actualArea, "Area of circle with radius 5 should be " + expectedArea);
    }
    @Test
    @Tag("invalid")
    public void testAreaWithNegativeRadius() {
        Circle circle = new Circle();
        circle.setRadius(-5.0);
        double actualArea = circle.getArea();
        assertTrue(Double.isNaN(actualArea), "Area of circle with negative radius should be NaN");
    }
}